apiVersion: v1 
kind: Pod 
metadata: 
  name: zookeeper 
  labels: 
    app: zk 
spec: 
  containers: 
  - name: zookeeper 
    image: zookeeper 
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    protocol: TCP
  selector:
    app: zk
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: cfkafka 
  labels: 
    app: kafka
spec: 
  containers: 
  - name: cfkafka 
    image: confluentinc/cp-kafka:5.3.0
    env:
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: "zkafka.ch.svc.cluster.local:2181"
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "PLAINTEXT://cfkafka.ch.svc.cluster.local:29092"
      - name: KAFKA_BROKER_ID
        value: "2"
      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: cfkafka
  labels:
    app: kafka
spec:
  ports:
  - port: 29092
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: zkafka 
  labels: 
    app: zk_kafka 
spec: 
  containers: 
  - name: zkafka 
    image: zookeeper 
---
apiVersion: v1
kind: Service
metadata:
  name: zkafka
  labels:
    app: zk_kafka
spec:
  ports:
  - port: 2181
    protocol: TCP
  selector:
    app: zk_kafka
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: clickhouse-ch1 
  labels: 
    app: ch1 
spec: 
  containers: 
  - name: clickhouse-ch1 
    image: clickhouse-ch1:v1
    imagePullPolicy: IfNotPresent
#  hostAliases:
#  - ip: "..."
#    hostnames:
#    - "kafka"
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: clickhouse-ch2 
  labels: 
    app: ch2 
spec: 
  containers: 
  - name: clickhouse-ch2 
    image: clickhouse-ch2:v1
#  hostAliases:
#  - ip: "..."
#    hostnames:
#    - "kafka"
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: clickhouse-ch3 
  labels: 
    app: ch3 
spec: 
  containers: 
  - name: clickhouse-ch3 
    image: clickhouse-ch3:v1
#  hostAliases:
#  - ip: "..."
#    hostnames:
#    - "kafka"
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: clickhouse-ch4 
  labels: 
    app: ch4 
spec: 
  containers: 
  - name: clickhouse-ch4 
    image: clickhouse-ch4:v1
#  hostAliases:
#  - ip: "..."
#    hostnames:
#    - "kafka"
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: clickhouse-ch5 
  labels: 
    app: ch5 
spec: 
  containers: 
  - name: clickhouse-ch5
    image: clickhouse-ch5:v1              
#  hostAliases:
#  - ip: "..."
#    hostnames:
#    - "kafka"
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch1-external
  labels:
    app: ch1
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
    nodePort: 30011
  - port: 8123
    name: "http-protocol"
    protocol: TCP
    nodePort: 30021
  selector:
    app: ch1
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch2-external
  labels:
    app: ch2
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
    nodePort: 30012
  - port: 8123
    name: "http-protocol"
    protocol: TCP
    nodePort: 30022
  selector:
    app: ch2
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch3-external
  labels:
    app: ch3
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
    nodePort: 30013
  - port: 8123
    name: "http-protocol"
    protocol: TCP
    nodePort: 30023
  selector:
    app: ch3
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch4-external
  labels:
    app: ch4
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
    nodePort: 30014
  - port: 8123
    name: "http-protocol"
    protocol: TCP
    nodePort: 30024
  selector:
    app: ch4
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch5-external
  labels:
    app: ch5
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
    nodePort: 30015
  - port: 8123
    name: "http-protocol"
    protocol: TCP
    nodePort: 30025
  selector:
    app: ch5         
  type: NodePort      
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch1
  labels:
    app: ch1
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
  - port: 8123
    name: "http-protocol"
    protocol: TCP
  - port: 9009
    name: "intra-ch-protocol"
    protocol: TCP
  selector:
    app: ch1
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch2
  labels:
    app: ch2
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
  - port: 8123
    name: "http-protocol"
    protocol: TCP
  - port: 9009
    name: "intra-ch-protocol"
    protocol: TCP
  selector:
    app: ch2
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch3
  labels:
    app: ch3
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
  - port: 8123
    name: "http-protocol"
    protocol: TCP
  - port: 9009
    name: "intra-ch-protocol"
    protocol: TCP
  selector:
    app: ch3
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch4
  labels:
    app: ch4
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
  - port: 8123
    name: "http-protocol"
    protocol: TCP
  - port: 9009
    name: "intra-ch-protocol"
    protocol: TCP
  selector:
    app: ch4
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ch5
  labels:
    app: ch5
spec:
  ports:
  - port: 9000
    name: "ch-protocol"
    protocol: TCP
  - port: 8123
    name: "http-protocol"
    protocol: TCP
  - port: 9009
    name: "intra-ch-protocol"
    protocol: TCP
  selector:
    app: ch5         
